# Generated by Django 4.1.5 on 2023-01-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('easy', '1'), ('medium', '2'), ('hard', '3')], max_length=10),
        ),
    ]
